//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace prjRentalManagement.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class eventOwner
    {
        [Display(Name = "Event ID")]
        public int eventId { get; set; }

        [Display(Name = "Manager ID")]
        public int managerId { get; set; }

        [Display(Name = "Owner ID")]
        public int ownerId { get; set; }

        [Display(Name = "Apartment ID")]
        public int apartmentId { get; set; }

        [Display(Name = "Event Created Date")]
        public System.DateTime eventDate { get; set; }

        [Required(ErrorMessage = "Description is required.")]
        [Display(Name = "Description")]
        public string description { get; set; }

        [Display(Name = "Event Status")]
        public string status { get; set; }
    
        public virtual apartment apartment { get; set; }
        public virtual manager manager { get; set; }
        public virtual owner owner { get; set; }
    }
}
