//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace prjRentalManagement.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class messageManager
    {

        public int messageId { get; set; }
        public int managerId { get; set; }
        public int tenantId { get; set; }

        [Required(ErrorMessage = "Message is required.")]
        [Display(Name = "Message")]

        public string message { get; set; }

        [Display(Name = "Response Message")]
        public string responseMessage { get; set; }
        public virtual manager manager { get; set; }
        public virtual tenant tenant { get; set; }
    }
}
