//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace prjRentalManagement.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DbPropertyRentalEntities : DbContext
    {
        public DbPropertyRentalEntities()
            : base("name=DbPropertyRentalEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<apartment> apartments { get; set; }
        public virtual DbSet<appointment> appointments { get; set; }
        public virtual DbSet<building> buildings { get; set; }
        public virtual DbSet<manager> managers { get; set; }
        public virtual DbSet<messageManager> messageManagers { get; set; }
        public virtual DbSet<messageOwner> messageOwners { get; set; }
        public virtual DbSet<owner> owners { get; set; }
        public virtual DbSet<tenant> tenants { get; set; }
    }
}
